import mongoose from "mongoose";

const expenseSchema = new mongoose.Schema(
  {
    tenant: { type: mongoose.Schema.Types.ObjectId, ref: "Tenant", required: true },
    description: { type: String, required: true, trim: true },
    category: {
      type: String,
      enum: ["Utilities", "Maintenance", "Service Charge", "Other"],
      default: "Other",
    },
    amount: { type: Number, required: true },
    status: { type: String, enum: ["pending", "paid"], default: "pending" },
    date: { type: Date, default: Date.now },
    autoGenerated: { type: Boolean, default: false },
    note: { type: String, trim: true },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User"},
  },
  { timestamps: true }
);

export default mongoose.model("Expense", expenseSchema);